services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: para_db
      POSTGRES_USER: para_user
      POSTGRES_PASSWORD: para_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U para_user -d para_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    environment:
      DATABASE_URL: postgresql://para_user:para_password@postgres:5432/para_db
      NODE_ENV: production
    ports:
      - "3001:3000"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
